# Generated by Django 6.0.6 on 2026-06-27 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0001_initial'),
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='folders',
            field=models.ManyToManyField(blank=True, related_name='notes', to='folders.folder'),
        ),
    ]
